#!/usr/bin/env bash

set -uo pipefail
set +e

env | sort

echo " ------------- "

pwd
ls

echo " ------------- "

env | docker run -i  docker.io/jmendiara/post-buildkite-plugin@sha256:5579b67a4d5cbe84ba7cb191e726b627f29565136bd0b14d9215b6e6803b3d32

echo " ------------- "
echo " COMIENZA LA EJECUCION "
echo " ------------- "

eval "${BUILDKITE_COMMAND}"
exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "Ha petado"
  exit $exit_code
fi

echo "Palante"

