#!/usr/bin/env bash

set -uo pipefail
set +e

env | sort

echo " ------------- "

pwd
ls

echo " ------------- "

env | docker run -i  docker.io/jmendiara/post-buildkite-plugin@sha256:fd7b2a3d0cfc3e96cbdab46b8c807bce734f77d74792de48332cb821a2741eb4

echo " ------------- "
echo " COMIENZA LA EJECUCION "
echo " ------------- "

eval "${BUILDKITE_COMMAND}"
exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "Ha petado"
  exit $exit_code
fi

echo "Palante"

