#!/usr/bin/env bash

set -uo pipefail
set +e





env | sort > plo.txt

cat plo.txt

echo " ------------- "

pwd
ls

echo " ------------- "

docker run --rm \
  -e BUILDKITE_PLUGIN_POST_POST_0_WHEN \
  -e BUILDKITE_PLUGIN_POST_POST_0_PIPELINE \
  -e BUILDKITE_PLUGIN_POST_POST_1_WHEN \
  -e BUILDKITE_PLUGIN_POST_POST_1_PIPELINE \
  -e BUILDKITE_PLUGIN_POST_POST_2_WHEN \
  -e BUILDKITE_PLUGIN_POST_POST_2_PIPELINE \
  docker.io/jmendiara/post-buildkite-plugin@sha256:4062636d46f64dcbefa08b23cfe33574038386c0965b3104e6e2f1ae474d4a21

echo " ------------- "
echo " COMIENZA LA EJECUCION "
echo " ------------- "

eval "${BUILDKITE_COMMAND}"
exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "Ha petado"
  exit $exit_code
fi

echo "Palante"

